#!/bin/bash

# prompt for Yes/No question

if [[ $# -ne 1 ]]; then
    echo "Usage: $(basename $0) <prompt>" >&2
    exit 1
fi

read -p "$1 (y/N) " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

exit 0

