#!/usr/bin/env python

""" Generate weekly report from time log.
"""

import datetime
from collections import defaultdict
import re
import os
import os.path
import logging
import sys
from optparse import OptionParser
from colorama import init, Fore, Back, Style


def format_effort(minutes):
    if minutes < 60:
        return '%dm' % minutes
    elif minutes < 480:
        return '%.1fh' % (float(minutes) / 60)
    else:
        return '%.2fd' % (float(minutes) / 480)


def format_category(category, minutes, **kwargs):
    if 'effort' in kwargs:
        if kwargs['format'] == 'markdown':
            effort = '  _[%s]_' % format_effort(minutes)
        else:
            effort = '  [%s]' % format_effort(minutes)
    else:
        effort = ''

    s = '%s%s' % (category, effort)

    if kwargs['format'] == 'markdown':
        return '%s\n%s\n' % (s, '=' * len(s))
    elif kwargs['format'] == 'color':
        return '%s%s%s' % (Fore.YELLOW, s, Fore.RESET)
    else:
        return s


def format_outcome(outcome, minutes, **kwargs):
    if 'effort' in kwargs:
        if kwargs['format'] == 'markdown':
            effort = '_[%s]_' % format_effort(minutes)
        else:
            effort = '[%s]' % format_effort(minutes)

        effort = '%7s  ' % effort
    else:
        effort = ''

    return '* %s%s.' % (effort, outcome)


usage_string = """Usage:  %prog [options] [YYYY/MM/DD]

%prog processes time log file and generates a weekly report
either for current week or for the week to which the date specified belongs.
"""

TRACK_FILE=os.path.join(os.getenv('HOME'), '.time-track.log')


prog = os.path.basename(sys.argv[0])
program_version = 1.0
version_string = "%%prog  %s" % program_version

logging.basicConfig(format = "%(asctime)s  " + prog +
                    ": %(levelname)s: %(message)s")


# parse command-line options

parser = OptionParser(usage = usage_string,
                      version = version_string)
#parser.add_option("-l", "--log",
#                  help = "redirect output to a log file",
#                  metavar = "FILE", dest = "log_file")
parser.add_option("-a", "--all", help = "display all categories",
                  action = "store_true", dest = "all_categories")
parser.add_option("-f", "--format", help = "output format",
                  default = "color", dest = "format")
parser.add_option("-v", "--verbose", help = "verbose operation",
                  action = "store_true", dest = "verbose_mode")

(options, args) = parser.parse_args()

if options.verbose_mode:
    logging.getLogger().setLevel(logging.DEBUG)
else:
    logging.getLogger().setLevel(logging.INFO)

as_of_date = datetime.datetime.today()

if len(args) == 1:
    as_of_date = None

    for fmt in ["%Y/%m/%d", "%m/%d/%Y", "%m/%d"]:
        try:
            as_of_date = datetime.datetime.strptime(args[0], fmt)
            break
        except:
            pass
elif len(args) != 0:
    parser.print_help()
    sys.exit()

if not as_of_date:
    logging.fatal('Bad as-of date: ' + args[0])
    sys.exit(1)

# derive start and end of the week
as_of_date = datetime.date(as_of_date.year, as_of_date.month, as_of_date.day)
wkday = as_of_date.weekday()
week_start = as_of_date + datetime.timedelta(days=-wkday)
week_end = as_of_date + datetime.timedelta(days=6-wkday)

activities = defaultdict(list)
minutes = defaultdict(float)

with open(TRACK_FILE, 'r') as fin:
    for line in fin:
        rec = [x.strip() for x in re.split('\s*\|\s*', line)]

        if len(rec) == 4:
            (category, outcome, effort) = (rec[2], rec[3], rec[1])
        elif len(rec) == 5:
            if rec[4] == '':
                (category, outcome, effort) = (rec[2], rec[3], rec[1])
            else:
                (category, outcome, effort) = (rec[2], rec[4], rec[1])
        else:
            continue

        # only process records for week in question

        try:
            rec_date = datetime.datetime.strptime(rec[0], "%m/%d/%Y").date()
        except:
            continue

        if rec_date < week_start or rec_date > week_end:
            continue

        activities[category].append((outcome, int(effort)))
        minutes[category] = minutes[category] + int(effort)


# output summary report

kwargs = { 'format' : options.format }

if options.verbose_mode:
    kwargs['effort'] = True

for key in sorted(activities.keys()):

    # skip personal categories
    if key == 'Personal':
        if not options.all_categories:
            continue;

    print(format_category(key, minutes[key], **kwargs))

    for outcome in activities[key]:
        print(format_outcome(outcome[0], outcome[1], **kwargs))

    print('')

sys.exit()


# Local Variables:
# compile-command: "pylint -r n gen-snippets"
# end:
