#!/bin/sh

# i3wm desktop management

# (from https://faq.i3wm.org/question/239/how-do-i-suspendlockscreen-and-logout.1.html)


lock() {
    # i3lock
    xscreensaver-command -lock
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}" >&2
        exit 2
esac

exit 0

